extends Node

const STRINGS := {
	"zh_Hans": {
		"menu_title": "无限王国",
		"menu_start": "开始",
		"menu_settings": "设置",
		"menu_gallery": "图鉴",
		"menu_about": "关于我们",
		"menu_quit": "退出游戏",
		"settings_title": "设置",
		"settings_language": "语言",
		"settings_display": "显示",
		"settings_audio": "音频",
		"settings_close": "关闭",
		"settings_hint": "F 全屏  |  W 窗口  |  V 垂直同步  |  Esc 关闭",
		"settings_status_fullscreen": "全屏",
		"settings_status_windowed": "窗口",
		"settings_mode_windowed": "窗口",
		"settings_mode_fullscreen": "全屏",
		"settings_vsync_on": "垂直同步 开",
		"settings_vsync_off": "垂直同步 关",
		"battle_pause": "战斗设置",
		"battle_resume": "继续战斗",
		"battle_exit": "退出到主菜单",
		"battle_char": "角色",
		"battle_escape": "撤退",
		"battle_inventory": "物品",
		"pause_title": "暂停中",
		"pause_resume_desc": "立刻回到战斗。",
		"pause_audio_desc": "不离开当前流程，直接调整章节混音。",
		"pause_settings_desc": "切换显示模式与同步选项。",
		"pause_restart_desc": "返回角色选择并重置本局流程。",
		"pause_quit_desc": "关闭游戏客户端。",
		"pause_restart_confirm": "再次按下返回选角即可放弃本局。Esc 取消。",
		"pause_quit_confirm": "再次按下退出游戏即可关闭客户端。Esc 取消。",
		"pause_restart_button": "返回选角",
		"pause_restart_confirm_button": "确认返回",
		"pause_quit_button": "退出游戏",
		"pause_quit_confirm_button": "确认退出",
		"pause_hint": "Esc 继续  |  A/F10 音频  |  S 设置  |  R 选角  |  Q 退出",
		"hud_map": "地图",
		"hud_accessory": "饰品",
		"hud_placeholder": "占位示意",
		"status_objective": "当前目标",
		"status_threat": "战场提示",
		"status_route": "路线",
		"status_relic": "饰品",
		"status_hero": "角色",
		"char_select_subtitle": "根据草图重排的像素风占位界面。先统一结构，再替换正式美术资源。",
		"char_actions": "开始 / 设置 / 图鉴 / 关于",
		"char_gallery_placeholder": "图鉴界面占位示意。\n后续可接入角色、敌人、饰品与路线条目。",
		"char_about_placeholder": "关于界面占位示意。\n后续可接入制作信息、版本与更新记录。",
		"char_hint": "1 / 2 / 3 选择角色  |  Enter 开始  |  S 设置  |  G 图鉴  |  A 关于  |  Q 退出",
		"placeholder_portrait": "角色立绘占位",
		"placeholder_card": "卡片占位",
		"placeholder_panel": "面板占位",
		"language_current": "当前语言",
		"audio_mix": "音频混音",
		"quit_game": "退出游戏",
		"restart_select": "返回选角",
		"run_summary": "本局概览",
		"gallery_title": "图鉴",
		"about_title": "关于我们",
		"accessory_preview": "预览",
		"accessory_preview_hint": "聚焦任意饰品后，这里会显示更详细的构筑建议。",
		"accessory_subtitle": "选择一个饰品。当前饰品会被立即替换，可用 1 / 2 / 3 快速选择。",
		"accessory_current": "当前饰品",
		"accessory_none": "无饰品",
		"accessory_keep": "保留当前",
		"accessory_keep_short": "保留",
		"accessory_reroll": "重抽 - {gold} 金币",
		"accessory_reroll_short": "重抽",
		"accessory_footer": "1 / 2 / 3 选择  |  K 保留  |  R 重抽 {gold} 金币  |  当前金币 {current_gold}  |  Esc 保留",
		"accessory_footer_short": "1-3 选择  |  K 保留  |  R 重抽",
		"result_continue": "继续",
		"result_quit": "退出游戏",
		"result_summary_missing": "暂无本局总结。",
		"result_timeline_missing": "暂无路线记录。",
		"result_victory_badge": "胜利结果",
		"result_defeat_badge": "失败结果",
		"result_relic_badge": "饰品结果",
		"result_badge": "结果面板",
		"event_route_label": "路线",
		"event_fit_label": "契合度",
		"event_shop_title": "黑市",
		"event_shop_subtitle": "花费金币，为下一段战斗拿到一个更明确的优势。",
		"event_bounty_title": "悬赏栏",
		"event_bounty_subtitle": "立刻拿钱，或把后续战斗的收益继续做高。",
		"event_rest_title": "教堂避难所",
		"event_rest_subtitle": "在下一场遭遇前恢复状态。",
		"event_training_title": "训练项目",
		"event_training_subtitle": "为本次流程选择一个长期强化方向。",
		"event_pact_title": "禁忌契约",
		"event_pact_subtitle": "拿到锋利收益，同时接受一项持续代价。",
		"event_attunement_title": "饰品共鸣",
		"event_attunement_subtitle": "当前饰品偏向 {path}。选择一个更贴合它的长期响应。",
		"event_scout_title": "侦查报告",
		"event_scout_subtitle": "为下一场战斗选择一个开局方案。",
		"event_travel_title": "旅途",
		"event_travel_subtitle": "当前没有可用事件。",
		"event_skip_continue": "继续前进",
		"event_skip_ignore": "忽略报告",
		"event_cost_free": "免费",
		"event_cost_gold": "花费 {gold} 金币",
		"event_footer_base": "1-{count} 选择",
		"event_footer_skip": "  |  Esc 跳过",
		"event_footer_shop": "{lead}  |  金币会立刻消耗。",
		"event_footer_bounty": "{lead}  |  奖励类效果会持续到本局结束。",
		"event_footer_rest": "{lead}  |  恢复会立刻生效。",
		"event_footer_training": "{lead}  |  训练加成会持续到本局结束。",
		"event_footer_pact": "{lead}  |  契约代价与收益都会保留。",
		"event_footer_attunement": "{lead}  |  共鸣会持续到本局结束。",
		"event_footer_scout": "{lead}  |  侦查预备会在下一战结束后消失。",
		"event_footer_travel": "{lead}  |  准备好后继续前进。",
		"audio_title": "音频混音",
		"audio_hint": "F10 切换面板  |  Esc 关闭",
		"audio_hint_short": "F10 切换  |  Esc 关闭",
		"audio_master_mute": "主音静音",
		"audio_master_muted": "主音已静音",
		"audio_reset": "重置",
		"audio_reset_full": "重置混音",
		"audio_reset_default": "恢复章节默认",
		"audio_close": "关闭"
	},
	"en": {
		"menu_title": "Infinity Kingdom",
		"menu_start": "Start",
		"menu_settings": "Settings",
		"menu_gallery": "Gallery",
		"menu_about": "About",
		"menu_quit": "Quit Game",
		"settings_title": "Settings",
		"settings_language": "Language",
		"settings_display": "Display",
		"settings_audio": "Audio",
		"settings_close": "Close",
		"settings_hint": "F Fullscreen  |  W Windowed  |  V VSync  |  Esc Close",
		"settings_status_fullscreen": "Fullscreen",
		"settings_status_windowed": "Windowed",
		"settings_mode_windowed": "Windowed",
		"settings_mode_fullscreen": "Fullscreen",
		"settings_vsync_on": "VSync On",
		"settings_vsync_off": "VSync Off",
		"battle_pause": "Battle Settings",
		"battle_resume": "Resume",
		"battle_exit": "Exit to Menu",
		"battle_char": "Character",
		"battle_escape": "Retreat",
		"battle_inventory": "Items",
		"pause_title": "Paused",
		"pause_resume_desc": "Return to the fight immediately.",
		"pause_audio_desc": "Adjust the current chapter mix without leaving the run.",
		"pause_settings_desc": "Switch fullscreen and sync options.",
		"pause_restart_desc": "Return to champion select and reset this run.",
		"pause_quit_desc": "Close the game client.",
		"pause_restart_confirm": "Press Champion Select again to abandon this run. Esc cancels.",
		"pause_quit_confirm": "Press Quit Game again to close the client. Esc cancels.",
		"pause_restart_button": "Champion Select",
		"pause_restart_confirm_button": "Confirm Select",
		"pause_quit_button": "Quit Game",
		"pause_quit_confirm_button": "Confirm Quit",
		"pause_hint": "Esc resume  |  A/F10 audio  |  S settings  |  R select  |  Q quit",
		"hud_map": "Map",
		"hud_accessory": "Accessory",
		"hud_placeholder": "Placeholder",
		"status_objective": "Objective",
		"status_threat": "Threat",
		"status_route": "Route",
		"status_relic": "Relic",
		"status_hero": "Hero",
		"char_select_subtitle": "Prototype layout rebuilt from the sketch. Structure first, final art later.",
		"char_actions": "Start / Settings / Gallery / About",
		"char_gallery_placeholder": "Gallery placeholder.\nLater this can hold heroes, enemies, relics, and route entries.",
		"char_about_placeholder": "About placeholder.\nLater this can hold credits, version notes, and update history.",
		"char_hint": "1 / 2 / 3 choose hero  |  Enter start  |  S settings  |  G gallery  |  A about  |  Q quit",
		"placeholder_portrait": "Portrait Placeholder",
		"placeholder_card": "Card Placeholder",
		"placeholder_panel": "Panel Placeholder",
		"language_current": "Current Language",
		"audio_mix": "Audio Mix",
		"quit_game": "Quit Game",
		"restart_select": "Champion Select",
		"run_summary": "Run Summary",
		"gallery_title": "Gallery",
		"about_title": "About",
		"accessory_preview": "Preview",
		"accessory_preview_hint": "Focus a relic to see a clearer build direction summary here.",
		"accessory_subtitle": "Equip one relic. The current relic is replaced immediately. Use 1 / 2 / 3 to choose fast.",
		"accessory_current": "Current Relic",
		"accessory_none": "No Accessory",
		"accessory_keep": "Keep Current",
		"accessory_keep_short": "Keep",
		"accessory_reroll": "Reroll - {gold} Gold",
		"accessory_reroll_short": "Reroll",
		"accessory_footer": "1 / 2 / 3 choose  |  K keep  |  R reroll {gold} gold  |  Gold {current_gold}  |  Esc keep",
		"accessory_footer_short": "1-3 choose  |  K keep  |  R reroll",
		"result_continue": "Continue",
		"result_quit": "Quit Game",
		"result_summary_missing": "Run summary unavailable.",
		"result_timeline_missing": "No route timeline recorded.",
		"result_victory_badge": "Victory Result",
		"result_defeat_badge": "Defeat Result",
		"result_relic_badge": "Relic Result",
		"result_badge": "Result Panel",
		"event_route_label": "Route",
		"event_fit_label": "Fit",
		"event_shop_title": "Black Market",
		"event_shop_subtitle": "Spend gold for a focused advantage before the next fight.",
		"event_bounty_title": "Bounty Board",
		"event_bounty_subtitle": "Take coin now, or lock in richer encounter payouts for the rest of this run.",
		"event_rest_title": "Church Refuge",
		"event_rest_subtitle": "Recover before the next encounter.",
		"event_training_title": "Training Drill",
		"event_training_subtitle": "Choose one stat technique for the rest of this run.",
		"event_pact_title": "Forbidden Pact",
		"event_pact_subtitle": "Take a sharp edge now, and live with the tradeoff for the rest of the run.",
		"event_attunement_title": "Relic Resonance",
		"event_attunement_subtitle": "Your relic leans toward {path}. Draw out one matching response for the rest of this run.",
		"event_scout_title": "Scout Report",
		"event_scout_subtitle": "Choose one battle plan for the next encounter.",
		"event_travel_title": "Travel",
		"event_travel_subtitle": "No event is available.",
		"event_skip_continue": "Continue",
		"event_skip_ignore": "Ignore the Report",
		"event_cost_free": "Free",
		"event_cost_gold": "Cost {gold} gold",
		"event_footer_base": "1-{count} choose",
		"event_footer_skip": "  |  Esc skip",
		"event_footer_shop": "{lead}  |  Gold is spent immediately.",
		"event_footer_bounty": "{lead}  |  Payout bonuses last for the rest of the run.",
		"event_footer_rest": "{lead}  |  Recovery resolves instantly.",
		"event_footer_training": "{lead}  |  Training stacks for the rest of the run.",
		"event_footer_pact": "{lead}  |  Pact tradeoffs are permanent.",
		"event_footer_attunement": "{lead}  |  Resonance lasts for the rest of the run.",
		"event_footer_scout": "{lead}  |  Scout prep expires when the next encounter ends.",
		"event_footer_travel": "{lead}  |  Continue when ready.",
		"audio_title": "Audio Mix",
		"audio_hint": "F10 toggle panel  |  Esc close",
		"audio_hint_short": "F10 toggle  |  Esc close",
		"audio_master_mute": "Master Mute",
		"audio_master_muted": "Master Muted",
		"audio_reset": "Reset",
		"audio_reset_full": "Reset Mix",
		"audio_reset_default": "Chapter Default",
		"audio_close": "Close"
	},
	"zh_Hant": {
		"menu_title": "無限王國",
		"menu_start": "開始",
		"menu_settings": "設定",
		"menu_gallery": "圖鑑",
		"menu_about": "關於我們",
		"menu_quit": "退出遊戲",
		"settings_title": "設定",
		"settings_language": "語言",
		"settings_display": "顯示",
		"settings_audio": "音訊",
		"settings_close": "關閉",
		"settings_hint": "F 全螢幕  |  W 視窗  |  V 垂直同步  |  Esc 關閉",
		"settings_status_fullscreen": "全螢幕",
		"settings_status_windowed": "視窗",
		"settings_mode_windowed": "視窗",
		"settings_mode_fullscreen": "全螢幕",
		"settings_vsync_on": "垂直同步 開",
		"settings_vsync_off": "垂直同步 關",
		"battle_pause": "戰鬥設定",
		"battle_resume": "繼續戰鬥",
		"battle_exit": "退出到主選單",
		"battle_char": "角色",
		"battle_escape": "撤退",
		"battle_inventory": "物品",
		"pause_title": "暫停中",
		"pause_resume_desc": "立刻回到戰鬥。",
		"pause_audio_desc": "不離開當前流程，直接調整章節混音。",
		"pause_settings_desc": "切換顯示模式與同步選項。",
		"pause_restart_desc": "返回角色選擇並重置本局流程。",
		"pause_quit_desc": "關閉遊戲客戶端。",
		"pause_restart_confirm": "再次按下返回選角即可放棄本局。Esc 取消。",
		"pause_quit_confirm": "再次按下退出遊戲即可關閉客戶端。Esc 取消。",
		"pause_restart_button": "返回選角",
		"pause_restart_confirm_button": "確認返回",
		"pause_quit_button": "退出遊戲",
		"pause_quit_confirm_button": "確認退出",
		"pause_hint": "Esc 繼續  |  A/F10 音訊  |  S 設定  |  R 選角  |  Q 退出",
		"hud_map": "地圖",
		"hud_accessory": "飾品",
		"hud_placeholder": "佔位示意",
		"status_objective": "目前目標",
		"status_threat": "戰場提示",
		"status_route": "路線",
		"status_relic": "飾品",
		"status_hero": "角色",
		"char_select_subtitle": "依照草圖重排的像素風佔位介面。先統一結構，再替換正式美術資源。",
		"char_actions": "開始 / 設定 / 圖鑑 / 關於",
		"char_gallery_placeholder": "圖鑑介面佔位示意。\n後續可接入角色、敵人、飾品與路線條目。",
		"char_about_placeholder": "關於介面佔位示意。\n後續可接入製作資訊、版本與更新記錄。",
		"char_hint": "1 / 2 / 3 選擇角色  |  Enter 開始  |  S 設定  |  G 圖鑑  |  A 關於  |  Q 退出",
		"placeholder_portrait": "角色立繪佔位",
		"placeholder_card": "卡片佔位",
		"placeholder_panel": "面板佔位",
		"language_current": "目前語言",
		"audio_mix": "音訊混音",
		"quit_game": "退出遊戲",
		"restart_select": "返回選角",
		"run_summary": "本局概覽",
		"gallery_title": "圖鑑",
		"about_title": "關於我們",
		"accessory_preview": "預覽",
		"accessory_preview_hint": "聚焦任意飾品後，這裡會顯示更詳細的構築建議。",
		"accessory_subtitle": "選擇一個飾品。當前飾品會被立即替換，可用 1 / 2 / 3 快速選擇。",
		"accessory_current": "當前飾品",
		"accessory_none": "無飾品",
		"accessory_keep": "保留當前",
		"accessory_keep_short": "保留",
		"accessory_reroll": "重抽 - {gold} 金幣",
		"accessory_reroll_short": "重抽",
		"accessory_footer": "1 / 2 / 3 選擇  |  K 保留  |  R 重抽 {gold} 金幣  |  當前金幣 {current_gold}  |  Esc 保留",
		"accessory_footer_short": "1-3 選擇  |  K 保留  |  R 重抽",
		"result_continue": "繼續",
		"result_quit": "退出遊戲",
		"result_summary_missing": "暫無本局總結。",
		"result_timeline_missing": "暫無路線記錄。",
		"result_victory_badge": "勝利結果",
		"result_defeat_badge": "失敗結果",
		"result_relic_badge": "飾品結果",
		"result_badge": "結果面板",
		"event_route_label": "路線",
		"event_fit_label": "契合度",
		"event_shop_title": "黑市",
		"event_shop_subtitle": "花費金幣，為下一段戰鬥拿到一個更明確的優勢。",
		"event_bounty_title": "懸賞欄",
		"event_bounty_subtitle": "立刻拿錢，或把後續戰鬥的收益繼續做高。",
		"event_rest_title": "教堂避難所",
		"event_rest_subtitle": "在下一場遭遇前恢復狀態。",
		"event_training_title": "訓練項目",
		"event_training_subtitle": "為本次流程選擇一個長期強化方向。",
		"event_pact_title": "禁忌契約",
		"event_pact_subtitle": "拿到鋒利收益，同時接受一項持續代價。",
		"event_attunement_title": "飾品共鳴",
		"event_attunement_subtitle": "當前飾品偏向 {path}。選擇一個更貼合它的長期響應。",
		"event_scout_title": "偵查報告",
		"event_scout_subtitle": "為下一場戰鬥選擇一個開局方案。",
		"event_travel_title": "旅途",
		"event_travel_subtitle": "當前沒有可用事件。",
		"event_skip_continue": "繼續前進",
		"event_skip_ignore": "忽略報告",
		"event_cost_free": "免費",
		"event_cost_gold": "花費 {gold} 金幣",
		"event_footer_base": "1-{count} 選擇",
		"event_footer_skip": "  |  Esc 跳過",
		"event_footer_shop": "{lead}  |  金幣會立刻消耗。",
		"event_footer_bounty": "{lead}  |  獎勵類效果會持續到本局結束。",
		"event_footer_rest": "{lead}  |  恢復會立刻生效。",
		"event_footer_training": "{lead}  |  訓練加成會持續到本局結束。",
		"event_footer_pact": "{lead}  |  契約代價與收益都會保留。",
		"event_footer_attunement": "{lead}  |  共鳴會持續到本局結束。",
		"event_footer_scout": "{lead}  |  偵查預備會在下一戰結束後消失。",
		"event_footer_travel": "{lead}  |  準備好後繼續前進。",
		"audio_title": "音訊混音",
		"audio_hint": "F10 切換面板  |  Esc 關閉",
		"audio_hint_short": "F10 切換  |  Esc 關閉",
		"audio_master_mute": "主音靜音",
		"audio_master_muted": "主音已靜音",
		"audio_reset": "重置",
		"audio_reset_full": "重置混音",
		"audio_reset_default": "恢復章節預設",
		"audio_close": "關閉"
	}
}

func text(key: String, replacements: Dictionary = {}) -> String:
	var locale_value := "zh_Hans"
	var tree := Engine.get_main_loop() as SceneTree
	if tree != null:
		var ui_settings := tree.root.get_node_or_null("/root/UISettings")
		if ui_settings != null and ui_settings.has_method("get_locale"):
			locale_value = str(ui_settings.get_locale())
	var locale_strings := STRINGS.get(locale_value, STRINGS["zh_Hans"]) as Dictionary
	var resolved := str(locale_strings.get(key, STRINGS["en"].get(key, key)))
	for replacement_key in replacements.keys():
		resolved = resolved.replace("{%s}" % str(replacement_key), str(replacements[replacement_key]))
	return resolved
